### ISSUE TITLE
LS47 and other alternate system customization

### ISSUE THREAD

**Issue by DonaldTsang** [dstein64/LC4#3]
Have LS47's 7x7 format (both English and Russian) as one of the defaults (see https://gitea.blesmrt.net/exa/ls47)
Might also be a good idea to include Greek 6x6 and 7x7, and maybe kana 7x7 and 8x8, but nobody has done such a design before.
Basic requirement: Flexible state sizes with a wider variety of lengths including 6 and 7, and flexible tiles that takes in a string as the default tile types and orientations.

**Comment by dstein64** [comment]
@DonaldTsang, these sound like nice ideas (although I'm unfamiliar with those algorithms), but beyond the intended scope and simplicity of this project.

**Comment by DonaldTsang** [comment]
@dstein64 I would not say it is out of scope due to LS47 being standardized for Russian
