### ISSUE TITLE
Visual simulation step-by-step

### ISSUE THREAD

**Issue by DonaldTsang** [dstein64/LC4#4]
A terminal cipher simulator/demonstration showing the encryption/decryption step-by-step.
It should look something like this (where the @ sign is the chess piece as an example), for example the English 6x6 version would look like 
```
#@ _  2  3  4  5  
6  7  8  9  a  b  
c  d  e  f  g  h    
i  j  k  l  m  n  
o  p  q  r  s  t  
u  v  w  x  y  z  
```

**Comment by dstein64** [comment]
@DonaldTsang, thanks for the nice idea.

This is implemented.

When calling `encrypt` or `decrypt`, there is now an optional `verbose` option that will result in a step-by-step algorithm visualization. The @ sign shows the current location, and the green highlighting shows the row and column that have shifted.

Here's a screenshot that captures the first few rows of example output:

<img width="309" alt="Screen Shot 2019-04-19 at 12 22 32 AM" src="https://user-images.githubusercontent.com/541289/56405226-65145500-6239-11e9-86cb-dde5bf52fbd0.png">

**Comment by DonaldTsang** [comment]
Nice!
