### ISSUE TITLE
Cross-Collaboration with other repos

### ISSUE THREAD

**Issue by DonaldTsang** [dstein64/LC4#5]
https://github.com/tonetheman/golang_lc4/issues/4 (Go)
https://github.com/Gavin-Song/elsie-four-cipher/issues/4 (JS)

**Comment by dstein64** [comment]
@DonaldTsang, can you please elaborate? It's not clear to me what the intent of your post is.

**Comment by DonaldTsang** [comment]
Standardize the process of presentation of LC4 with certain features like visual representation, implementation of key-setting, initializing vector and checksum (which exists in the paper) and extra features like LS47 and other mutli-lingual support.

**Comment by dstein64** [comment]
@DonaldTsang, thanks for providing further details.

Given the simplicity of the current API (below) and that this algorithm is primarily for human-based encryption/decryption, I think the benefits of a standardized API would not be worth the effort of coordinating and implementing this.

Current LC4 API in this repo:
```
lc4.encrypt(key, text, [nonce], [verbose])
lc4.decrypt(key, cyphertext, [nonce], [verbose])
```
